

name: spa-stack-webapi-ng

services:
  
  spa-ng-webapi:
    image: idstudios/spa-stack-webapi-angular:1.0.0
    build: .
    container_name: 'spa-webapi-ng'
    restart: no
    ports: 
      - 8090:8090
    environment:
      - CONNECTIONSTRINGS__ERPDBCONNECTIONSTRING=${CONNECTIONSTRINGS__ERPDBCONNECTIONSTRING}
      - CONNECTIONSTRINGS__USERDBCONNECTIONSTRING=${CONNECTIONSTRINGS__USERDBCONNECTIONSTRING}
      - CONNECTIONSTRINGS__SHIPRDBCONNECTIONSTRING=${CONNECTIONSTRINGS__SHIPRDBCONNECTIONSTRING}
      - GOOGLECLIENTID=${GOOGLECLIENTID}
      - GOOGLECLIENTSECRET=${GOOGLECLIENTSECRET}
      - MICROSOFTCLIENTID=${MICROSOFTCLIENTID}
      - MICROSOFTCLIENTSECRET=${MICROSOFTCLIENTSECRET}
      - KAFKABOOTSTRAPSERVERS=${KAFKABOOTSTRAPSERVERS}
      - KAFKASCHEMAREGISTRYURL=${KAFKASCHEMAREGISTRYURL}
      - ASPNETCORE_URLS=https://0.0.0.0:8090 #for local development and testing
#      - ASPNETCORE_URLS=http://0.0.0.0:8090 #for externally hosted Ingress LB HTTPS, aka Kubernetes


 
