// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace io.idstudios.flink.models
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e")]
	public partial class WebOrder : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""WebOrder"",""namespace"":""io.idstudios.flink.models"",""fields"":[{""name"":""web_order_id"",""type"":""string""},{""name"":""order_date"",""type"":""long""},{""name"":""customer_name"",""type"":""string""},{""name"":""destination"",""type"":""string""},{""name"":""product_id"",""type"":""int""},{""name"":""quantity"",""type"":""int""}]}");
		private string _web_order_id;
		private long _order_date;
		private string _customer_name;
		private string _destination;
		private int _product_id;
		private int _quantity;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return WebOrder._SCHEMA;
			}
		}
		public string web_order_id
		{
			get
			{
				return this._web_order_id;
			}
			set
			{
				this._web_order_id = value;
			}
		}
		public long order_date
		{
			get
			{
				return this._order_date;
			}
			set
			{
				this._order_date = value;
			}
		}
		public string customer_name
		{
			get
			{
				return this._customer_name;
			}
			set
			{
				this._customer_name = value;
			}
		}
		public string destination
		{
			get
			{
				return this._destination;
			}
			set
			{
				this._destination = value;
			}
		}
		public int product_id
		{
			get
			{
				return this._product_id;
			}
			set
			{
				this._product_id = value;
			}
		}
		public int quantity
		{
			get
			{
				return this._quantity;
			}
			set
			{
				this._quantity = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.web_order_id;
			case 1: return this.order_date;
			case 2: return this.customer_name;
			case 3: return this.destination;
			case 4: return this.product_id;
			case 5: return this.quantity;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.web_order_id = (System.String)fieldValue; break;
			case 1: this.order_date = (System.Int64)fieldValue; break;
			case 2: this.customer_name = (System.String)fieldValue; break;
			case 3: this.destination = (System.String)fieldValue; break;
			case 4: this.product_id = (System.Int32)fieldValue; break;
			case 5: this.quantity = (System.Int32)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
